% exercise 5.1.3

% Fit classification tree
T = fitctree(X, classNames(y+1), ...
    'splitcriterion', 'deviance', ...
    'categorical', 1:M, ...
    'PredictorNames', attributeNames, ...
    'prune', 'off', ...
    'minparent', 1);

% View the tree
view(T,'Mode','graph')
