% exercise 5.1.2

% Fit classification tree
T = fitctree(X, classNames(y+1), ...    
    'splitcriterion', 'gdi', ...
    'categorical', 1:M, ...
    'PredictorNames', attributeNames, ...
    'prune', 'off', ...
    'minparent', 1);

% View the tree
view(T,'Mode','graph')